steps:
  - label: ":snake: Generate Sentence"
    key: "sentence"
    command:
      - pip install loremipsum
      - python -c "import loremipsum; result = loremipsum.sentence(max_char=20); print(result); open('result.txt','w').write(result)"
      - buildkite-agent annotate "$(cat result.txt)" --style "info" --context "sentence"
    plugins:
      - docker#v5.11.0:
          image: "python:3.11"
          mount-buildkite-agent: true
          propagate-environment: true

  - label: ":snake: Generate Paragraph"
    key: "paragraph"
    depends_on: "sentence"
    command:
      - pip install loremipsum
      - python -c "import loremipsum; result = loremipsum.paragraph(max_char=100); print(result); open('result2.txt','w').write(result)"
      - buildkite-agent annotate "$(cat result2.txt)" --style "success" --context "paragraph"
      - buildkite-agent artifact upload result2.txt
    plugins:
      - docker#v5.11.0:
          image: "python:3.11"
          mount-buildkite-agent: true
          propagate-environment: true
  
  - label: ":open_file_folder: Download and Print Artifact"
    key: "download"
    depends_on: "paragraph"
    command:
      - buildkite-agent artifact download result2.txt .
      - cat result2.txt

  # - label: ":docker: Build and Push to Package Registry"
  #   depends_on: "download"
  #   command:
  #     - docker build --load -t packages.buildkite.com/$BUILDKITE_ORGANIZATION_SLUG/py-lorem-registry/py-lorem:$BUILDKITE_BUILD_NUMBER .
  #     - buildkite-agent secret get REGISTRY_TOKEN | docker login packages.buildkite.com -u buildkite --password-stdin
  #     - docker push packages.buildkite.com/$BUILDKITE_ORGANIZATION_SLUG/py-lorem-registry/py-lorem:$BUILDKITE_BUILD_NUMBER

      #     command:
      # - docker build -t packages.buildkite.com/$${BUILDKITE_ORGANIZATION_SLUG}/py-lorem-registry/py-lorem:$${BUILDKITE_BUILD_NUMBER} .
      # - docker login packages.buildkite.com -u buildkite -p $${REGISTRY_TOKEN}
      # - docker push packages.buildkite.com/$${BUILDKITE_ORGANIZATION_SLUG}/py-lorem-registry/py-lorem:$${BUILDKITE_BUILD_NUMBER}